spring.application.name=bff-libroclases
server.port=8083


# URLs de los microservicios
ms-academico.url=http://localhost:8081/api/v1
ms-asistencia.url=http://localhost:8082/api/v1

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Actuator 
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always

# Resilience4j - Circuit Breaker para academico
resilience4j.circuitbreaker.instances.academico.register-health-indicator=true
resilience4j.circuitbreaker.instances.academico.sliding-window-size=10
resilience4j.circuitbreaker.instances.academico.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.academico.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.academico.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.academico.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.academico.automatic-transition-from-open-to-half-open-enabled=true

# Resilience4j - Circuit Breaker para asistencia
resilience4j.circuitbreaker.instances.asistencia.register-health-indicator=true
resilience4j.circuitbreaker.instances.asistencia.sliding-window-size=10
resilience4j.circuitbreaker.instances.asistencia.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.asistencia.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.asistencia.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.asistencia.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.asistencia.automatic-transition-from-open-to-half-open-enabled=true


