spring.application.name=bff-libroclases
server.port=8083

spring.profiles.default=mysql

spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret=LibroClasesBffSecretKeyParaEvaluacionFullstack2026MuyLarga
app.jwt.expiration-ms=28800000

# Usuario inspector predeterminado (se crea al iniciar si no existe en la BD)
app.usuario-inicial.nombre-usuario=inspector
app.usuario-inicial.email=inspector@colegiobo.cl
app.usuario-inicial.password=clave123
app.usuario-inicial.rol=INSPECTOR

# Usuario profesor predeterminado (se crea al iniciar si no existe en la BD)
app.profesor-inicial.nombre-usuario=profesor
app.profesor-inicial.email=profesor@colegiobo.cl
app.profesor-inicial.password=clave123

# Eureka (arrancar eureka-server en 8761 primero)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# El BFF resuelve estos nombres via Eureka + LoadBalancer
ms-academico.service-id=ms-academico
ms-asistencia.service-id=ms-asistencia
ms-academico.api-path=/api/v1
ms-asistencia.api-path=/api/v1

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.persistAuthorization=true

# Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always

# Resilience4j - Circuit Breaker para academico
resilience4j.circuitbreaker.instances.academico.register-health-indicator=true
resilience4j.circuitbreaker.instances.academico.sliding-window-size=10
resilience4j.circuitbreaker.instances.academico.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.academico.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.academico.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.academico.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.academico.automatic-transition-from-open-to-half-open-enabled=true

# Resilience4j - Circuit Breaker para asistencia
resilience4j.circuitbreaker.instances.asistencia.register-health-indicator=true
resilience4j.circuitbreaker.instances.asistencia.sliding-window-size=10
resilience4j.circuitbreaker.instances.asistencia.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.asistencia.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.asistencia.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.asistencia.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.asistencia.automatic-transition-from-open-to-half-open-enabled=true
